question_data = [
    {"category": "Entertainment: Japanese Anime & Manga",
     "type": "boolean",
     "difficulty": "easy",
     "question": "In the 1988 film &quot;Akira&quot;, Tetsuo ends up destroying Tokyo.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]
     },
    {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
                                       "question": "Hippopotomonstrosesquippedaliophobia is the irrational fear of long words.",
                                       "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Animals", "type": "boolean", "difficulty": "medium",
     "question": "The Ceratosaurus, a dinosaur known for having a horn on the top of its nose, is also known to be a decendent of the Tyrannosaurus Rex.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "There are 6 legendary cards in &quot;Clash Royale&quot;.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Science: Mathematics", "type": "boolean", "difficulty": "hard",
                                      "question": "If you could fold a piece of paper in half 50 times, its&#039; thickness will be 3\/4th the distance from the Earth to the Sun.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Animals", "type": "boolean", "difficulty": "medium", "question": "The Platypus is a mammal.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Politics", "type": "boolean", "difficulty": "medium",
     "question": "During the 2016 United States presidential election, the State of California possessed the most electoral votes, having 55.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Politics", "type": "boolean", "difficulty": "easy",
     "question": "Donald Trump won the popular vote in the 2016 United States presidential election.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Television", "type": "boolean", "difficulty": "medium",
     "question": "In &quot;Star Trek&quot;, Klingons are commonly referred to as &quot;Black Elves&quot;.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "Several characters in &quot;Super Mario 64&quot; blink their eyes, including Mario himself.",
     "correct_answer": "True", "incorrect_answers": ["False"]}
]
